############################################
#                                          #
#                DesertedStaff                 #
# Configuration for staff related commands #
#                                          #
############################################

# Staff online message
staffMsg: '&6The current staff member(s) online are: %STAFF%'

# Permission required to be considered "staff" by /staff
staffPerm: 'desertedstaff.staff'

# The message sent when punishments are listed
punishments:
  - '&6Hacking: Ban 7d'
  - '&6Hacking extended: Ban 30d'
  - '&6Staff disrespect: Mute 1d'

# Staff mode toggled on
staffOn: '&bStaff mode has been enabled.'

# Staff mode toggled off
staffOff: '&bStaff mode has been disabled.'

# Build mode toggled on
buildOn: '&bBuild mode has been enabled.'

# Build mode toggled off
buildOff: '&bBuild mode has been disabled.'

# No permission message
noPermission: '&cYou do not have permission for this command'

# Not a player message
notPlayer: '&cYou must be a player to execute this command'

# If true, build mode will be enabled. Placing/Destroying blocks
# will be disabled unless the player is in build mode
# This also disables crop trampling 
enableBuildMode: true

# Staff chat on
staffCOn: '&bStaff chat has been toggled on.'

# Staff chat off
staffCOff: '&bStaff chat has been toggled off.'

# Staff chat format
staffFormat: '&8[&4Staff&8] %PLAYER%: %MSG%'

# Ban usage
banUsage: '&cInvalid usage. Use: /ban <player> <reason>'

# Player not online
notOnline: '&cThat player is not online'

# Default ban message
defaultBan: '&cBanned by administrator'

# The ban format
banFormat:
  - "&cYou have been banned."
  - "&7Reason: &6%REASON%"
  - "&7Staff member: %STAFF%"
  - "&7End: %END%"
  - "%APPEAL%"

# Perm ban
banNeverEnd: '&cNEVER'

# user may appeal
yesAppeal: '&7You may appeal'

# User may not appeal
noAppeal: '&cYou not not appeal'

# Banned player
bannedPlayer: '&cYou have banned %PLAYER%'

# Staff banned player
staffBan: '&8[&cStaff&8] &7%STAFF% has banned %PLAYER%'

# Player is already banned
pBanned: '&cPlayer already banned'

# Unban cmd usage
unbanUsage: '&cInvalid usage. Please use: /unban <player>'

# Player not banned
notBanned: '&cThat player is not banned'

# Unbanned a player
unbannedPlayer: '&bYou have unbanned %PLAYER%'

# DO NOT EDIT. This is the config update system
configVersion: '0.0.3'