name: DesertedStaff
version: 0.0.l
main: codes.matthewp.desertedstaff.DesertedStaff

depend: [DesertedCore]

commands:
  staffmode:
    description: Turn on/off staff mode.
  staff:
    description: See online staff members
  buildmode:
    description: Turn on/off build mode.
  punishments:
    description: View punishments.
  staffchat:
    desctiption: Toggle staff chat on/off
  s:
    description: Send a message to staff chat without it being toggled on
  ban:
    description: Ban a player